# -*- coding: utf-8 -*-
"""searchbar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WAOtMTFB7d7U0ix4biXumiTmWaWu1783
"""

from flask import Flask, request, jsonify
import joblib  # Import joblib untuk memuat model

app = Flask(__name__)

# Memuat kembali TF-IDF Vectorizer
tfidf_vectorizer = joblib.load('tfidf_vectorizer.pkl')

# Fungsi pencarian berbasis teks
def cari_tempat_laundry(keyword, data):
    # Transform kata kunci menjadi vektor TF-IDF
    keyword_vec = tfidf_vectorizer.transform([keyword.lower()])

    # Hitung similaritas kosinus antara keyword_vec dan semua dokumen
    similarities = cosine_similarity(keyword_vec, tfidf_matrix).flatten()

    # Dapatkan indeks urutan similaritas tertinggi
    index_sorted = similarities.argsort()[::-1]

    # Ambil data tempat laundry yang paling relevan
    hasil_pencarian = data.iloc[index_sorted]

    return hasil_pencarian

# API endpoint untuk pencarian
@app.route('/search', methods=['GET'])
def search():
    keyword = request.args.get('keyword')
    hasil = cari_tempat_laundry(keyword, data)
    hasil_json = hasil[['Name', 'Fulladdress', 'phone', 'Average Rating', 'Google Maps URL', 'Website', 'Opening Hours', 'Featured Image', 'Layanan']].to_dict(orient='records')
    return jsonify(hasil_json)

if __name__ == '__main__':
    app.run(debug=True)